In [ ]:
# Import Packages

import os
import json
import pandas as pd
import mysql.connector

# Aggregated_Transaction

path = "C:/Users/matfr/OneDrive/Desktop/PhonePhe/pulse/data/aggregated/transaction/country/india/state/"
agg_tran_list = os.listdir(path)

# Mapping between abbreviated and full state names
state_mapping = {
    'andaman-&-nicobar-islands': 'Andaman & Nicobar',
    'andhra-pradesh':'Andhra Pradesh',
    'arunachal-pradesh':'Arunachal Pradesh',
    'assam':'Assam',
    'bihar':'Bihar',
    'chandigarh':'Chandigarh',
    'chhattisgarh':'Chhattisgarh',
    'dadra-&-nagar-haveli-&-daman-&-diu':'Dadra and Nagar Haveli and Daman and Diu',
    'delhi':'Delhi',
    'goa':'Goa',
    'gujarat':'Gujarat',
    'haryana':'Haryana',
    'himachal-pradesh':'Himachal Pradesh',
    'jammu-&-kashmir':'Jammu & Kashmir',
    'jharkhand':'Jharkhand',
    'karnataka':'Karnataka',
    'kerala':'Kerala',
    'ladakh':'Ladakh',
    'lakshadweep':'Lakshadweep',
    'madhya-pradesh':'Madhya Pradesh',
    'maharashtra':'Maharashtra',
    'manipur':'Manipur',
    'meghalaya':'Meghalaya',
    'mizoram':'Mizoram',
    'nagaland':'Nagaland',
    'odisha':'Odisha',
    'puducherry':'Puducherry',
    'punjab':'Punjab',
    'rajasthan':'Rajasthan',
    'sikkim':'Sikkim',
    'tamil-nadu':'Tamil Nadu',
    'telangana':'Telangana',
    'tripura':'Tripura',
    'uttar-pradesh':'Uttarakhand',
    'uttarakhand':'Uttarakhand',
    'west-bengal':'West Bengal',

}

columns1 = {"States": [], "Years": [], "Quarter": [], "Transaction_Type": [], "Transaction_Count": [], "Transaction_Amount": []}

for states in agg_tran_list:
    cur_states = path + states + "/"
    agg_year_list = os.listdir(cur_states)

    for year in agg_year_list:
        cur_year = cur_states + year + "/"
        agg_file_list = os.listdir(cur_year)

        for file in agg_file_list:
            cur_file = cur_year + file
            data = open(cur_file, "r")
            A = json.load(data)

            for i in A["data"]["transactionData"]:
                name = i["name"]
                count = i["paymentInstruments"][0]["count"]
                amount = i["paymentInstruments"][0]["amount"]
                columns1["Transaction_Type"].append(name)
                columns1["Transaction_Count"].append(count)
                columns1["Transaction_Amount"].append(amount)
                columns1["States"].append(states)
                columns1["Years"].append(year)
                columns1["Quarter"].append(int(file.strip(".json")))

# Create DataFrame
aggregated_Transaction = pd.DataFrame(columns1)

# Replace abbreviated state names with full names
aggregated_Transaction['States'] = aggregated_Transaction['States'].map(state_mapping)

# Display the updated DataFrame
aggregated_Transaction



# <------->Aggregated_User<------->

path1 = "C:/Users/matfr/OneDrive/Desktop/PhonePhe/pulse/data/aggregated/user/country/india/state/"
agg_user_list = os.listdir(path1)

# Mapping between abbreviated and full state names
state_mapping = {
    'andaman-&-nicobar-islands': 'Andaman & Nicobar',
    'andhra-pradesh':'Andhra Pradesh',
    'arunachal-pradesh':'Arunachal Pradesh',
    'assam':'Assam',
    'bihar':'Bihar',
    'chandigarh':'Chandigarh',
    'chhattisgarh':'Chhattisgarh',
    'dadra-&-nagar-haveli-&-daman-&-diu':'Dadra and Nagar Haveli and Daman and Diu',
    'delhi':'Delhi',
    'goa':'Goa',
    'gujarat':'Gujarat',
    'haryana':'Haryana',
    'himachal-pradesh':'Himachal Pradesh',
    'jammu-&-kashmir':'Jammu & Kashmir',
    'jharkhand':'Jharkhand',
    'karnataka':'Karnataka',
    'kerala':'Kerala',
    'ladakh':'Ladakh',
    'lakshadweep':'Lakshadweep',
    'madhya-pradesh':'Madhya Pradesh',
    'maharashtra':'Maharashtra',
    'manipur':'Manipur',
    'meghalaya':'Meghalaya',
    'mizoram':'Mizoram',
    'nagaland':'Nagaland',
    'odisha':'Odisha',
    'puducherry':'Puducherry',
    'punjab':'Punjab',
    'rajasthan':'Rajasthan',
    'sikkim':'Sikkim',
    'tamil-nadu':'Tamil Nadu',
    'telangana':'Telangana',
    'tripura':'Tripura',
    'uttar-pradesh':'Uttarakhand',
    'uttarakhand':'Uttarakhand',
    'west-bengal':'West Bengal',

}

columns2 = {"States": [], "Years": [], "Quarter": [], "Brands": [], "Transaction_Count": [], "Percentages": []}

for states in agg_user_list:
    cur_states = path1 + states + "/"
    agg_year_list = os.listdir(cur_states)

    for year in agg_year_list:
        cur_year = cur_states + year + "/"
        agg_file_list = os.listdir(cur_year)

        for file in agg_file_list:
            cur_file = cur_year + file
            data = open(cur_file, "r")
            B = json.load(data)
            
            try:
                for i in B["data"]["usersByDevice"]:
                    brand = i["brand"]
                    count = i["count"]
                    percentage = i["percentage"]
                    columns2["Brands"].append(brand)
                    columns2["Transaction_Count"].append(count)
                    columns2["Percentages"].append(percentage)
                    columns2["States"].append(states)
                    columns2["Years"].append(year)
                    columns2["Quarter"].append(int(file.strip(".json")))
                    
            except:
                pass
                
                #if you run without try block, it will be get error likes(TypeError: 'NoneType' object is not iterable)
                #(How to handle None, use try block)

                
#columns2
Aggregated_User=pd.DataFrame(columns2)

Aggregated_User['States'] = Aggregated_User['States'].map(state_mapping)
Aggregated_User



# <------->Aggregated_insurance<------->

path2="C:/Users/matfr/OneDrive/Desktop/PhonePhe/pulse/data/aggregated/insurance/country/india/state/"

agg_insur_list = os.listdir(path2)

# Mapping between abbreviated and full state names
state_mapping = {
    'andaman-&-nicobar-islands': 'Andaman & Nicobar',
    'andhra-pradesh':'Andhra Pradesh',
    'arunachal-pradesh':'Arunachal Pradesh',
    'assam':'Assam',
    'bihar':'Bihar',
    'chandigarh':'Chandigarh',
    'chhattisgarh':'Chhattisgarh',
    'dadra-&-nagar-haveli-&-daman-&-diu':'Dadra and Nagar Haveli and Daman and Diu',
    'delhi':'Delhi',
    'goa':'Goa',
    'gujarat':'Gujarat',
    'haryana':'Haryana',
    'himachal-pradesh':'Himachal Pradesh',
    'jammu-&-kashmir':'Jammu & Kashmir',
    'jharkhand':'Jharkhand',
    'karnataka':'Karnataka',
    'kerala':'Kerala',
    'ladakh':'Ladakh',
    'lakshadweep':'Lakshadweep',
    'madhya-pradesh':'Madhya Pradesh',
    'maharashtra':'Maharashtra',
    'manipur':'Manipur',
    'meghalaya':'Meghalaya',
    'mizoram':'Mizoram',
    'nagaland':'Nagaland',
    'odisha':'Odisha',
    'puducherry':'Puducherry',
    'punjab':'Punjab',
    'rajasthan':'Rajasthan',
    'sikkim':'Sikkim',
    'tamil-nadu':'Tamil Nadu',
    'telangana':'Telangana',
    'tripura':'Tripura',
    'uttar-pradesh':'Uttarakhand',
    'uttarakhand':'Uttarakhand',
    'west-bengal':'West Bengal',

}

columns3 = {"States": [], "Years": [], "Quarter": [], "Transaction_Type": [], "Transaction_Count": [], "Transaction_Amount": []}

for states in agg_insur_list:
    cur_states = path2 + states + "/"
    agg_year_list = os.listdir(cur_states)

    for year in agg_year_list:
        cur_year = cur_states + year + "/"
        agg_file_list = os.listdir(cur_year)

        for file in agg_file_list:
            cur_file = cur_year + file
            data = open(cur_file, "r")
            C = json.load(data)
            
            
            for i in C["data"]["transactionData"]:
                name = i["name"]
                count = i["paymentInstruments"][0]["count"]
                amount = i["paymentInstruments"][0]["amount"]
                columns3["Transaction_Type"].append(name)
                columns3["Transaction_Count"].append(count)
                columns3["Transaction_Amount"].append(amount)
                columns3["States"].append(states)
                columns3["Years"].append(year)
                columns3["Quarter"].append(int(file.strip(".json")))
                
Aggregated_insurance=pd.DataFrame(columns3)

Aggregated_insurance['States'] = Aggregated_insurance['States'].map(state_mapping)

Aggregated_insurance



# <------->Map_Transaction<------->

path3="C:/Users/matfr/OneDrive/Desktop/PhonePhe/pulse/data/map/transaction/hover/country/india/state/"

map_trans_list = os.listdir(path3)

# Mapping between abbreviated and full state names
state_mapping = {
    'andaman-&-nicobar-islands': 'Andaman & Nicobar',
    'andhra-pradesh':'Andhra Pradesh',
    'arunachal-pradesh':'Arunachal Pradesh',
    'assam':'Assam',
    'bihar':'Bihar',
    'chandigarh':'Chandigarh',
    'chhattisgarh':'Chhattisgarh',
    'dadra-&-nagar-haveli-&-daman-&-diu':'Dadra and Nagar Haveli and Daman and Diu',
    'delhi':'Delhi',
    'goa':'Goa',
    'gujarat':'Gujarat',
    'haryana':'Haryana',
    'himachal-pradesh':'Himachal Pradesh',
    'jammu-&-kashmir':'Jammu & Kashmir',
    'jharkhand':'Jharkhand',
    'karnataka':'Karnataka',
    'kerala':'Kerala',
    'ladakh':'Ladakh',
    'lakshadweep':'Lakshadweep',
    'madhya-pradesh':'Madhya Pradesh',
    'maharashtra':'Maharashtra',
    'manipur':'Manipur',
    'meghalaya':'Meghalaya',
    'mizoram':'Mizoram',
    'nagaland':'Nagaland',
    'odisha':'Odisha',
    'puducherry':'Puducherry',
    'punjab':'Punjab',
    'rajasthan':'Rajasthan',
    'sikkim':'Sikkim',
    'tamil-nadu':'Tamil Nadu',
    'telangana':'Telangana',
    'tripura':'Tripura',
    'uttar-pradesh':'Uttarakhand',
    'uttarakhand':'Uttarakhand',
    'west-bengal':'West Bengal',

}


columns4 = {"States": [], "Years": [], "Quarter": [], "Districts": [], "Transaction_Count": [], "Transaction_Amount": []}

for states in map_trans_list:
    cur_states = path3 + states + "/"
    map_year_list = os.listdir(cur_states)

    for year in map_year_list:
        cur_year = cur_states + year + "/"
        map_file_list = os.listdir(cur_year)

        for file in map_file_list:
            cur_file = cur_year + file
            data = open(cur_file, "r")
            D = json.load(data)
            #print(D)-Use in for lopp
            
#D["data"]- This and below query use and run in new cell, then only you get idea
#D["hoverDataList"]
#D["data"]["hoverDataList"][0]
#D["data"]["hoverDataList"][0]["metric"][0]
#D["data"]["hoverDataList"][0]["metric"][0]["count"]
            
            for i in D["data"]["hoverDataList"]:
                name = i["name"]
                count = i["metric"][0]["count"]
                amount = i["metric"][0]["amount"]
                columns4["Districts"].append(name)
                columns4["Transaction_Count"].append(count)
                columns4["Transaction_Amount"].append(amount)
                columns4["States"].append(states)
                columns4["Years"].append(year)
                columns4["Quarter"].append(int(file.strip(".json")))
                
#print(D["data"]["hoverDataList"][0]["name"])
#print(D["data"]["hoverDataList"][0]["metric"][0]["count"])
#print(D["data"]["hoverDataList"][0]["metric"][0]["amount"])

#columns4

Map_Transaction=pd.DataFrame(columns4)

Map_Transaction['States'] = Map_Transaction['States'].map(state_mapping)

Map_Transaction


# <------->Map_User<------->

path4="C:/Users/matfr/OneDrive/Desktop/PhonePhe/pulse/data/map/user/hover/country/india/state/"

map_user_list = os.listdir(path4)

# Mapping between abbreviated and full state names
state_mapping = {
    'andaman-&-nicobar-islands': 'Andaman & Nicobar',
    'andhra-pradesh':'Andhra Pradesh',
    'arunachal-pradesh':'Arunachal Pradesh',
    'assam':'Assam',
    'bihar':'Bihar',
    'chandigarh':'Chandigarh',
    'chhattisgarh':'Chhattisgarh',
    'dadra-&-nagar-haveli-&-daman-&-diu':'Dadra and Nagar Haveli and Daman and Diu',
    'delhi':'Delhi',
    'goa':'Goa',
    'gujarat':'Gujarat',
    'haryana':'Haryana',
    'himachal-pradesh':'Himachal Pradesh',
    'jammu-&-kashmir':'Jammu & Kashmir',
    'jharkhand':'Jharkhand',
    'karnataka':'Karnataka',
    'kerala':'Kerala',
    'ladakh':'Ladakh',
    'lakshadweep':'Lakshadweep',
    'madhya-pradesh':'Madhya Pradesh',
    'maharashtra':'Maharashtra',
    'manipur':'Manipur',
    'meghalaya':'Meghalaya',
    'mizoram':'Mizoram',
    'nagaland':'Nagaland',
    'odisha':'Odisha',
    'puducherry':'Puducherry',
    'punjab':'Punjab',
    'rajasthan':'Rajasthan',
    'sikkim':'Sikkim',
    'tamil-nadu':'Tamil Nadu',
    'telangana':'Telangana',
    'tripura':'Tripura',
    'uttar-pradesh':'Uttarakhand',
    'uttarakhand':'Uttarakhand',
    'west-bengal':'West Bengal',

}

columns5 = {"States": [], "Years": [], "Quarter": [], "Districts": [], "RegisteredUsers": [], "AppOpens": []}

for states in map_user_list:
    cur_states = path4 + states + "/"
    map_year_list = os.listdir(cur_states)

    for year in map_year_list:
        cur_year = cur_states + year + "/"
        map_file_list = os.listdir(cur_year)

        for file in map_file_list:
            cur_file = cur_year + file
            data = open(cur_file, "r")
            E = json.load(data)
            #print(E)Use in for lopp
            
#E["data"]- This and below query use and run in new cell, then only you get idea
#E["data"]["hoverData"]
#for i in E["data"]["hoverData"].items():
    #print(i[0])
    #print(i[1])
    #print(i[1]["registeredUsers"])
    #print(i[1]["appOpens"])
    
            for i in E["data"]["hoverData"].items():
                districts = i[0]
                registeredUsers = i[1]["registeredUsers"]
                appOpens = i[1]["appOpens"]
                columns5["Districts"].append(districts)
                columns5["RegisteredUsers"].append(registeredUsers)
                columns5["AppOpens"].append(appOpens)
                columns5["States"].append(states)
                columns5["Years"].append(year)
                columns5["Quarter"].append(int(file.strip(".json")))
                
#columns5
Map_User=pd.DataFrame(columns5)

Map_User['States'] = Map_User['States'].map(state_mapping)
Map_User


# <------->Map_Insurance<------->

path5= "C:/Users/matfr/OneDrive/Desktop/PhonePhe/pulse/data/map/insurance/hover/country/india/state/"

map_insurance_list = os.listdir(path5)

# Mapping between abbreviated and full state names
state_mapping = {
    'andaman-&-nicobar-islands': 'Andaman & Nicobar',
    'andhra-pradesh':'Andhra Pradesh',
    'arunachal-pradesh':'Arunachal Pradesh',
    'assam':'Assam',
    'bihar':'Bihar',
    'chandigarh':'Chandigarh',
    'chhattisgarh':'Chhattisgarh',
    'dadra-&-nagar-haveli-&-daman-&-diu':'Dadra and Nagar Haveli and Daman and Diu',
    'delhi':'Delhi',
    'goa':'Goa',
    'gujarat':'Gujarat',
    'haryana':'Haryana',
    'himachal-pradesh':'Himachal Pradesh',
    'jammu-&-kashmir':'Jammu & Kashmir',
    'jharkhand':'Jharkhand',
    'karnataka':'Karnataka',
    'kerala':'Kerala',
    'ladakh':'Ladakh',
    'lakshadweep':'Lakshadweep',
    'madhya-pradesh':'Madhya Pradesh',
    'maharashtra':'Maharashtra',
    'manipur':'Manipur',
    'meghalaya':'Meghalaya',
    'mizoram':'Mizoram',
    'nagaland':'Nagaland',
    'odisha':'Odisha',
    'puducherry':'Puducherry',
    'punjab':'Punjab',
    'rajasthan':'Rajasthan',
    'sikkim':'Sikkim',
    'tamil-nadu':'Tamil Nadu',
    'telangana':'Telangana',
    'tripura':'Tripura',
    'uttar-pradesh':'Uttarakhand',
    'uttarakhand':'Uttarakhand',
    'west-bengal':'West Bengal',

}

columns6 = {"States": [], "Years": [], "Quarter": [], "Districts": [], "Transaction_Count": [], "Transaction_Amount": []}

for states in map_insurance_list:
    cur_states = path5 + states + "/"
    map_year_list = os.listdir(cur_states)

    for year in map_year_list:
        cur_year = cur_states + year + "/"
        map_file_list = os.listdir(cur_year)

        for file in map_file_list:
            cur_file = cur_year + file
            data = open(cur_file, "r")
            F = json.load(data)
            #print(F)
            
            
            for i in F["data"]["hoverDataList"]:
                name = i["name"]
                count = i["metric"][0]["count"]
                amount = i["metric"][0]["amount"]
                columns6["Districts"].append(name)
                columns6["Transaction_Count"].append(count)
                columns6["Transaction_Amount"].append(amount)
                columns6["States"].append(states)
                columns6["Years"].append(year)
                columns6["Quarter"].append(int(file.strip(".json")))
                
#columns6

Map_Insurance=pd.DataFrame(columns6)

Map_Insurance['States'] = Map_Insurance['States'].map(state_mapping)
Map_Insurance


# <------->Top_Transaction<------->

path6="C:/Users/matfr/OneDrive/Desktop/PhonePhe/pulse/data/top/transaction/country/india/state/"

top_transaction_list = os.listdir(path6)

# Mapping between abbreviated and full state names
state_mapping = {
    'andaman-&-nicobar-islands': 'Andaman & Nicobar',
    'andhra-pradesh':'Andhra Pradesh',
    'arunachal-pradesh':'Arunachal Pradesh',
    'assam':'Assam',
    'bihar':'Bihar',
    'chandigarh':'Chandigarh',
    'chhattisgarh':'Chhattisgarh',
    'dadra-&-nagar-haveli-&-daman-&-diu':'Dadra and Nagar Haveli and Daman and Diu',
    'delhi':'Delhi',
    'goa':'Goa',
    'gujarat':'Gujarat',
    'haryana':'Haryana',
    'himachal-pradesh':'Himachal Pradesh',
    'jammu-&-kashmir':'Jammu & Kashmir',
    'jharkhand':'Jharkhand',
    'karnataka':'Karnataka',
    'kerala':'Kerala',
    'ladakh':'Ladakh',
    'lakshadweep':'Lakshadweep',
    'madhya-pradesh':'Madhya Pradesh',
    'maharashtra':'Maharashtra',
    'manipur':'Manipur',
    'meghalaya':'Meghalaya',
    'mizoram':'Mizoram',
    'nagaland':'Nagaland',
    'odisha':'Odisha',
    'puducherry':'Puducherry',
    'punjab':'Punjab',
    'rajasthan':'Rajasthan',
    'sikkim':'Sikkim',
    'tamil-nadu':'Tamil Nadu',
    'telangana':'Telangana',
    'tripura':'Tripura',
    'uttar-pradesh':'Uttarakhand',
    'uttarakhand':'Uttarakhand',
    'west-bengal':'West Bengal',

}

columns7 = {"States": [], "Years": [], "Quarter": [], "Pincodes": [], "Transaction_Count": [], "Transaction_Amount": []}

for states in top_transaction_list:
    cur_states = path6 + states + "/"
    top_year_list = os.listdir(cur_states)

    for year in top_year_list:
        cur_year = cur_states + year + "/"
        top_file_list = os.listdir(cur_year)

        for file in top_file_list:
            cur_file = cur_year + file
            data = open(cur_file, "r")
            G = json.load(data)
            #print(G)
            
            for i in G["data"]["pincodes"]:
                entityName = i["entityName"]
                count = i["metric"]["count"]
                amount = i["metric"]["amount"]
                columns7["Pincodes"].append(entityName)
                columns7["Transaction_Count"].append(count)
                columns7["Transaction_Amount"].append(amount)
                columns7["States"].append(states)
                columns7["Years"].append(year)
                columns7["Quarter"].append(int(file.strip(".json")))
                
#columns7
          
Top_Transaction=pd.DataFrame(columns7)

Top_Transaction['States'] = Top_Transaction['States'].map(state_mapping)

Top_Transaction



# <------->Top_User<------->

path7 = "C:/Users/matfr/OneDrive/Desktop/PhonePhe/pulse/data/top/user/country/india/state/"

top_user_list = os.listdir(path7)

# Mapping between abbreviated and full state names
state_mapping = {
    'andaman-&-nicobar-islands': 'Andaman & Nicobar',
    'andhra-pradesh':'Andhra Pradesh',
    'arunachal-pradesh':'Arunachal Pradesh',
    'assam':'Assam',
    'bihar':'Bihar',
    'chandigarh':'Chandigarh',
    'chhattisgarh':'Chhattisgarh',
    'dadra-&-nagar-haveli-&-daman-&-diu':'Dadra and Nagar Haveli and Daman and Diu',
    'delhi':'Delhi',
    'goa':'Goa',
    'gujarat':'Gujarat',
    'haryana':'Haryana',
    'himachal-pradesh':'Himachal Pradesh',
    'jammu-&-kashmir':'Jammu & Kashmir',
    'jharkhand':'Jharkhand',
    'karnataka':'Karnataka',
    'kerala':'Kerala',
    'ladakh':'Ladakh',
    'lakshadweep':'Lakshadweep',
    'madhya-pradesh':'Madhya Pradesh',
    'maharashtra':'Maharashtra',
    'manipur':'Manipur',
    'meghalaya':'Meghalaya',
    'mizoram':'Mizoram',
    'nagaland':'Nagaland',
    'odisha':'Odisha',
    'puducherry':'Puducherry',
    'punjab':'Punjab',
    'rajasthan':'Rajasthan',
    'sikkim':'Sikkim',
    'tamil-nadu':'Tamil Nadu',
    'telangana':'Telangana',
    'tripura':'Tripura',
    'uttar-pradesh':'Uttarakhand',
    'uttarakhand':'Uttarakhand',
    'west-bengal':'West Bengal',

}

columns8 = {"States": [], "Years": [], "Quarter": [], "Pincodes": [], "RegisteredUser": []}

for states in top_user_list:
    cur_states = path7 + states + "/"
    top_year_list = os.listdir(cur_states)

    for year in top_year_list:
        cur_year = cur_states + year + "/"
        top_file_list = os.listdir(cur_year)

        for file in top_file_list:
            cur_file = cur_year + file
            data = open(cur_file, "r")
            H = json.load(data)
            
            for i in H["data"]["pincodes"]:
                name = i["name"]
                registeredusers = i["registeredUsers"]  # Fix the variable name here
                columns8["Pincodes"].append(name)
                columns8["RegisteredUser"].append(registeredusers)  # Fix the variable name here
                columns8["States"].append(states)
                columns8["Years"].append(year)
                columns8["Quarter"].append(int(file.strip(".json")))

Top_User = pd.DataFrame(columns8)

Top_User['States'] = Top_User['States'].map(state_mapping)

Top_User




# <------->Top_Insurance<------->

path8="C:/Users/matfr/OneDrive/Desktop/PhonePhe/pulse/data/top/insurance/country/india/state/"

top_insurance_list = os.listdir(path8)

# Mapping between abbreviated and full state names
state_mapping = {
    'andaman-&-nicobar-islands': 'Andaman & Nicobar',
    'andhra-pradesh':'Andhra Pradesh',
    'arunachal-pradesh':'Arunachal Pradesh',
    'assam':'Assam',
    'bihar':'Bihar',
    'chandigarh':'Chandigarh',
    'chhattisgarh':'Chhattisgarh',
    'dadra-&-nagar-haveli-&-daman-&-diu':'Dadra and Nagar Haveli and Daman and Diu',
    'delhi':'Delhi',
    'goa':'Goa',
    'gujarat':'Gujarat',
    'haryana':'Haryana',
    'himachal-pradesh':'Himachal Pradesh',
    'jammu-&-kashmir':'Jammu & Kashmir',
    'jharkhand':'Jharkhand',
    'karnataka':'Karnataka',
    'kerala':'Kerala',
    'ladakh':'Ladakh',
    'lakshadweep':'Lakshadweep',
    'madhya-pradesh':'Madhya Pradesh',
    'maharashtra':'Maharashtra',
    'manipur':'Manipur',
    'meghalaya':'Meghalaya',
    'mizoram':'Mizoram',
    'nagaland':'Nagaland',
    'odisha':'Odisha',
    'puducherry':'Puducherry',
    'punjab':'Punjab',
    'rajasthan':'Rajasthan',
    'sikkim':'Sikkim',
    'tamil-nadu':'Tamil Nadu',
    'telangana':'Telangana',
    'tripura':'Tripura',
    'uttar-pradesh':'Uttarakhand',
    'uttarakhand':'Uttarakhand',
    'west-bengal':'West Bengal',

}

columns9 = {"States": [], "Years": [], "Quarter": [], "Pincodes": [], "Transaction_count": [], "Transaction_amount": []}


for states in top_insurance_list:
    cur_states = path8 + states + "/"
    top_year_list = os.listdir(cur_states)

    for year in top_year_list:
        cur_year = cur_states + year + "/"
        top_file_list = os.listdir(cur_year)

        for file in top_file_list:
            cur_file = cur_year + file
            data = open(cur_file, "r")
            J = json.load(data)
            
            
            for i in J["data"]["pincodes"]:
                name = i["entityName"]
                count = i["metric"]["count"]
                amount = i["metric"]["amount"]
                columns9["Pincodes"].append(name)
                columns9["Transaction_count"].append(count)
                columns9["Transaction_amount"].append(amount)
                columns9["States"].append(states)
                columns9["Years"].append(year)
                columns9["Quarter"].append(int(file.strip(".json")))
                
Top_Insurance=pd.DataFrame(columns9)

Top_Insurance['States'] = Top_Insurance['States'].map(state_mapping)

Top_Insurance



# <------->MySQL Create Database<------->

# Create database query is below query(NOTE: remove # )

#mydb = mysql.connector.connect(host="127.0.0.1", user="root", password="Mattpop")

#cursor = mydb.cursor()
#cursor.execute("create database Phonepe")
#mydb.commit()



# <------->Aggregated Insurance Table<------->


mydb = mysql.connector.connect(host="127.0.0.1", user="root", password="Mattpop", database="Phonepe")

cursor = mydb.cursor()


create_query1= '''CREATE TABLE if not exists aggre_insurance (States varchar(50),
                                                                      Years int,
                                                                      Quarter int,
                                                                      Transaction_Type varchar(50),
                                                                      Transaction_Count bigint,
                                                                      Transaction_Amount bigint
                                                                      )'''
cursor.execute(create_query1)
mydb.commit()

for index, row in Aggregated_insurance.iterrows():
    insert_query1 = '''
        INSERT INTO aggre_insurance (States, Years, Quarter, Transaction_Type, Transaction_Count, Transaction_Amount)
        VALUES (%s, %s, %s, %s, %s, %s)
    '''
    
    values = (
        row['States'],
        row['Years'],
        row['Quarter'],
        row['Transaction_Type'],
        row['Transaction_Count'],
        row['Transaction_Amount']
    )
    
    cursor.execute(insert_query1, values)
    mydb.commit()

    
    
# <------->Aggregated Transaction Table<------->


mydb = mysql.connector.connect(host="127.0.0.1", user="root", password="Mattpop", database="Phonepe")

cursor = mydb.cursor()


create_query2= '''CREATE TABLE if not exists aggre_Transaction (States varchar(50),
                                                                      Years int,
                                                                      Quarter int,
                                                                      Transaction_Type varchar(50),
                                                                      Transaction_Count bigint,
                                                                      Transaction_Amount bigint
                                                                      )'''
cursor.execute(create_query2)
mydb.commit()

for index, row in aggregated_Transaction.iterrows():
    
    insert_query1 = '''
        INSERT INTO aggre_Transaction (States, Years, Quarter, Transaction_Type, Transaction_Count, Transaction_Amount)
        VALUES (%s, %s, %s, %s, %s, %s)
    '''
    
    values = (
        row['States'],
        row['Years'],
        row['Quarter'],
        row['Transaction_Type'],
        row['Transaction_Count'],
        row['Transaction_Amount']
    )
    
    cursor.execute(insert_query1, values)
    mydb.commit()
    
    
    
# <------->Aggregated User Table<------->

mydb = mysql.connector.connect(host="127.0.0.1", user="root", password="Mattpop", database="Phonepe")

cursor = mydb.cursor()


create_query3= '''CREATE TABLE if not exists aggre_User (States varchar(50),
                                                                  Years int,
                                                                  Quarter int,
                                                                  Brands varchar(50),
                                                                  Transaction_Count bigint,
                                                                  Percentages float
                                                                  )'''
cursor.execute(create_query3)
mydb.commit()


for index, row in Aggregated_User.iterrows():
    insert_query1 = '''
        INSERT INTO  aggre_User (States, Years, Quarter, Brands, Transaction_Count, Percentages)
        VALUES (%s, %s, %s, %s, %s, %s)
    '''
    
    values = (
        row['States'],
        row['Years'],
        row['Quarter'],
        row['Brands'],
        row['Transaction_Count'],
        row['Percentages']
    )
    
    cursor.execute(insert_query1, values)
    mydb.commit()
    
    

    
# <------->Map_Transaction_Table<------->


mydb = mysql.connector.connect(host="127.0.0.1", user="root", password="Mattpop", database="Phonepe")

cursor = mydb.cursor()

create_query4= '''CREATE TABLE if not exists Map_trans (States varchar(50),
                                                                  Years int,
                                                                  Quarter int,
                                                                  Districts varchar(50),
                                                                  Transaction_Count bigint,
                                                                  Transaction_Amount bigint
                                                                  )'''

cursor.execute(create_query4)
mydb.commit()

for index, row in Map_Transaction.iterrows():
    insert_query1 = '''
        INSERT INTO  Map_trans (States, Years, Quarter, Districts, Transaction_Count, Transaction_Amount)
        VALUES (%s, %s, %s, %s, %s, %s)
    '''
    
    values = (
        row['States'],
        row['Years'],
        row['Quarter'],
        row['Districts'],
        row['Transaction_Count'],
        row['Transaction_Amount']
    )
    
    cursor.execute(insert_query1, values)
    mydb.commit()
    
    
# <------->Map_User_Table<------->


mydb = mysql.connector.connect(host="127.0.0.1", user="root", password="Mattpop", database="Phonepe")

cursor = mydb.cursor()

create_query5= '''CREATE TABLE if not exists Map_user (States varchar(50),
                                                                  Years int,
                                                                  Quarter int,
                                                                  Districts varchar(50),
                                                                  RegisteredUsers bigint,
                                                                  AppOpens bigint
                                                                  )'''

cursor.execute(create_query5)
mydb.commit()


for index, row in Map_User.iterrows():
    insert_query1 = '''
        INSERT INTO  Map_user (States, Years, Quarter, Districts, RegisteredUsers, AppOpens)
        VALUES (%s, %s, %s, %s, %s, %s)
    '''
    
    values = (
        row['States'],
        row['Years'],
        row['Quarter'],
        row['Districts'],
        row['RegisteredUsers'],
        row['AppOpens']
    )
    
    cursor.execute(insert_query1, values)
    mydb.commit()
    
    
    
# <------->Map_Insurance_Table<------->

mydb = mysql.connector.connect(host="127.0.0.1", user="root", password="Mattpop", database="Phonepe")

cursor = mydb.cursor()

create_query6= '''CREATE TABLE if not exists Map_insur (States varchar(50),
                                                                  Years int,
                                                                  Quarter int,
                                                                  Districts varchar(50),
                                                                  Transaction_Count bigint,
                                                                  Transaction_Amount bigint
                                                                  )'''

cursor.execute(create_query6)
mydb.commit()


for index, row in Map_Insurance.iterrows():
    insert_query1 = '''
        INSERT INTO  Map_insur (States, Years, Quarter, Districts, Transaction_Count, Transaction_Amount)
        VALUES (%s, %s, %s, %s, %s, %s)
    '''
    
    values = (
        row['States'],
        row['Years'],
        row['Quarter'],
        row['Districts'],
        row['Transaction_Count'],
        row['Transaction_Amount']
    )
    
    cursor.execute(insert_query1, values)
    mydb.commit()
    
    
    
# <------->Top_Transaction_Table<------->


mydb = mysql.connector.connect(host="127.0.0.1", user="root", password="Mattpop", database="Phonepe")

cursor = mydb.cursor()

create_query7= '''CREATE TABLE if not exists Top_trans (States varchar(50),
                                                                  Years int,
                                                                  Quarter int,
                                                                  Pincodes int,
                                                                  Transaction_Count bigint,
                                                                  Transaction_Amount bigint
                                                                  )'''

cursor.execute(create_query7)
mydb.commit()


for index, row in Top_Transaction.iterrows():
    insert_query1 = '''
        INSERT INTO  Top_trans (States, Years, Quarter, Pincodes, Transaction_Count, Transaction_Amount)
        VALUES (%s, %s, %s, %s, %s, %s)
    '''
    
    values = (
        row['States'],
        row['Years'],
        row['Quarter'],
        row['Pincodes'],
        row['Transaction_Count'],
        row['Transaction_Amount']
    )
    
    cursor.execute(insert_query1, values)
    mydb.commit()
    
    
    
# <------->Top_User_Tables<------->



mydb = mysql.connector.connect(host="127.0.0.1", user="root", password="Mattpop", database="Phonepe")

cursor = mydb.cursor()

create_query8= '''CREATE TABLE if not exists Top_users (States varchar(50),
                                                                  Years int,
                                                                  Quarter int,
                                                                  Pincodes int,
                                                                  RegisteredUser bigint
                                                                  )'''

cursor.execute(create_query8)
mydb.commit()

for index, row in Top_User.iterrows():
    insert_query1 = '''
        INSERT INTO  Top_users (States, Years, Quarter, Pincodes, RegisteredUser)
        VALUES (%s, %s, %s, %s, %s)
    '''
    
    values = (
        row['States'],
        row['Years'],
        row['Quarter'],
        row['Pincodes'],
        row['RegisteredUser']
    )
    
    cursor.execute(insert_query1, values)
    mydb.commit()
    
    
    
# <------->Top_Insurance_Tables<------->

mydb = mysql.connector.connect(host="127.0.0.1", user="root", password="Mattpop", database="Phonepe")

cursor = mydb.cursor()

create_query9= '''CREATE TABLE if not exists Top_Insur (States varchar(50),
                                                                  Years int,
                                                                  Quarter int,
                                                                  Pincodes int,
                                                                  Transaction_count bigint,
                                                                  Transaction_amount bigint
                                                                  )'''

cursor.execute(create_query9)
mydb.commit()

for index, row in Top_Insurance.iterrows():
    insert_query1 = '''
        INSERT INTO  Top_Insur (States, Years, Quarter, Pincodes, Transaction_count,Transaction_amount)
        VALUES (%s, %s, %s, %s, %s,%s)
    '''
    
    values = (
        row['States'],
        row['Years'],
        row['Quarter'],
        row['Pincodes'],
        row['Transaction_count'],
        row['Transaction_amount']
    )
    
    cursor.execute(insert_query1, values)
    mydb.commit()